spring.application.name=Notesshala
spring.datasource.url=jdbc:mysql://localhost:3306/noteshala
spring.datasource.username=root
spring.datasource.password=Ksnr@#3108

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


noteshala.upload-dir=./uploads

spring.servlet.multipart.enabled=true

spring.servlet.multipart.max-file-size=200MB



